import Link from "next/link";
import { ArrowLeft, Bot, Shield, Eye, AlertTriangle } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "AI Disclosure | CreatorPersonaAI",
    description: "Transparency about AI technology used in CreatorPersonaAI — EU AI Act compliance.",
};

export default function AIDisclosurePage() {
    return (
        <div className="min-h-screen bg-background text-foreground">
            {/* Header */}
            <header className="border-b border-border/30 bg-muted/10">
                <div className="max-w-4xl mx-auto px-6 py-4 flex items-center gap-3">
                    <Link href="/dashboard" className="text-muted-foreground hover:text-foreground transition-colors">
                        <ArrowLeft className="w-5 h-5" />
                    </Link>
                    <h1 className="text-lg font-semibold">AI Transparency & Disclosure</h1>
                </div>
            </header>

            {/* Content */}
            <main className="max-w-4xl mx-auto px-6 py-12">
                <div className="prose prose-invert prose-sm max-w-none space-y-8">
                    <div>
                        <p className="text-muted-foreground text-sm">Last updated: February 15, 2026</p>
                    </div>

                    {/* Important Notice Banner */}
                    <div className="bg-gradient-to-r from-violet-500/10 via-purple-500/10 to-pink-500/10 border border-violet-500/30 rounded-xl p-6">
                        <div className="flex items-start gap-3">
                            <Bot className="w-6 h-6 text-violet-400 mt-0.5 shrink-0" />
                            <div>
                                <h2 className="text-lg font-bold text-foreground mb-2">All Content is AI-Generated</h2>
                                <p className="text-muted-foreground leading-relaxed">
                                    CreatorPersonaAI is a fully AI-powered platform. Every influencer persona, image, video,
                                    script, and voice produced by this platform is <strong className="text-foreground">entirely generated by artificial intelligence</strong>.
                                    No real people are depicted in any generated content unless a user explicitly uploads their own image.
                                </p>
                            </div>
                        </div>
                    </div>

                    <section className="space-y-4">
                        <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
                            <Shield className="w-5 h-5 text-violet-400" />
                            AI Technologies Used
                        </h2>
                        <p className="text-muted-foreground leading-relaxed">
                            We believe in full transparency about the AI technologies powering our platform:
                        </p>

                        <div className="grid gap-4 sm:grid-cols-2">
                            <div className="bg-muted/20 border border-border/30 rounded-lg p-4">
                                <h3 className="font-semibold text-foreground mb-1">🖼️ Image Generation</h3>
                                <p className="text-sm text-muted-foreground">
                                    <strong>fal.ai (FLUX / PuLID)</strong> — Generates photorealistic influencer avatars
                                    and reference photos. PuLID preserves facial identity across different scenes.
                                </p>
                            </div>
                            <div className="bg-muted/20 border border-border/30 rounded-lg p-4">
                                <h3 className="font-semibold text-foreground mb-1">🎬 Video Generation</h3>
                                <p className="text-sm text-muted-foreground">
                                    <strong>Kling AI</strong> — Produces short-form marketing videos with lip-synced
                                    speech from a single reference image.
                                </p>
                            </div>
                            <div className="bg-muted/20 border border-border/30 rounded-lg p-4">
                                <h3 className="font-semibold text-foreground mb-1">✍️ Text & Script Generation</h3>
                                <p className="text-sm text-muted-foreground">
                                    <strong>OpenRouter (Claude AI)</strong> — Creates influencer personalities, backstories,
                                    video scripts, and marketing copy.
                                </p>
                            </div>
                            <div className="bg-muted/20 border border-border/30 rounded-lg p-4">
                                <h3 className="font-semibold text-foreground mb-1">🎤 Voice Generation</h3>
                                <p className="text-sm text-muted-foreground">
                                    <strong>ElevenLabs</strong> — Generates realistic AI voices for video narration
                                    with natural-sounding speech patterns.
                                </p>
                            </div>
                        </div>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
                            <Eye className="w-5 h-5 text-violet-400" />
                            EU AI Act Compliance
                        </h2>
                        <p className="text-muted-foreground leading-relaxed">
                            In accordance with the European Union Artificial Intelligence Act (EU AI Act), we provide
                            the following disclosures:
                        </p>
                        <ul className="text-muted-foreground space-y-2 list-disc list-inside">
                            <li>
                                <strong className="text-foreground">Transparency:</strong> All AI-generated content is clearly labeled
                                as such within our platform. We recommend users maintain this labeling when sharing content externally.
                            </li>
                            <li>
                                <strong className="text-foreground">Risk Category:</strong> Our AI system is classified as a
                                limited-risk AI system that generates synthetic media content. We implement appropriate transparency
                                obligations.
                            </li>
                            <li>
                                <strong className="text-foreground">Human Oversight:</strong> Users retain full control over what
                                content is generated, reviewed, and published. No content is automatically published without user action.
                            </li>
                            <li>
                                <strong className="text-foreground">Deepfake Provisions:</strong> Under Article 52(3) of the AI Act,
                                AI-generated content that could be mistaken for authentic content must be disclosed. Users are required
                                to label AI-generated content when sharing publicly.
                            </li>
                        </ul>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
                            <AlertTriangle className="w-5 h-5 text-amber-400" />
                            User Obligations for AI Content
                        </h2>
                        <div className="bg-amber-500/10 border border-amber-500/30 rounded-lg p-4 space-y-3">
                            <p className="text-amber-200 font-medium">
                                When sharing AI-generated content from CreatorPersonaAI, you must:
                            </p>
                            <ul className="text-muted-foreground space-y-2 list-decimal list-inside">
                                <li>
                                    <strong>Label content as AI-generated</strong> — Use hashtags like <code className="bg-muted/30 px-1 rounded">#AIGenerated</code>,{" "}
                                    <code className="bg-muted/30 px-1 rounded">#AICreated</code>, or equivalent platform labels
                                </li>
                                <li>
                                    <strong>Do not impersonate real people</strong> — AI influencers must not be presented as real individuals
                                </li>
                                <li>
                                    <strong>Follow platform policies</strong> — TikTok, Instagram, YouTube and LinkedIn all have specific
                                    policies regarding AI-generated content disclosure
                                </li>
                                <li>
                                    <strong>Review before publishing</strong> — Always review AI-generated content for accuracy and appropriateness
                                </li>
                            </ul>
                        </div>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-xl font-bold text-foreground">Platform-Specific Disclosure Requirements</h2>
                        <div className="space-y-3">
                            <div className="bg-muted/20 border border-border/30 rounded-lg p-4">
                                <h3 className="font-semibold text-foreground">TikTok</h3>
                                <p className="text-sm text-muted-foreground">
                                    Use the &quot;AI-generated content&quot; label in TikTok&apos;s content disclosure settings.
                                    Add <code className="bg-muted/30 px-1 rounded">#AIGenerated</code> in the caption.
                                </p>
                            </div>
                            <div className="bg-muted/20 border border-border/30 rounded-lg p-4">
                                <h3 className="font-semibold text-foreground">Instagram / Meta</h3>
                                <p className="text-sm text-muted-foreground">
                                    Use Meta&apos;s &quot;Made with AI&quot; label for AI-generated images and videos.
                                    Include disclosure in the post caption.
                                </p>
                            </div>
                            <div className="bg-muted/20 border border-border/30 rounded-lg p-4">
                                <h3 className="font-semibold text-foreground">YouTube</h3>
                                <p className="text-sm text-muted-foreground">
                                    Enable the &quot;Altered or synthetic content&quot; disclosure in YouTube Studio for
                                    all AI-generated videos uploaded to the platform.
                                </p>
                            </div>
                            <div className="bg-muted/20 border border-border/30 rounded-lg p-4">
                                <h3 className="font-semibold text-foreground">LinkedIn</h3>
                                <p className="text-sm text-muted-foreground">
                                    Clearly state in the post that content features an AI-generated persona.
                                    Use <code className="bg-muted/30 px-1 rounded">#AIContent</code> hashtag.
                                </p>
                            </div>
                        </div>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-xl font-bold text-foreground">Contact</h2>
                        <p className="text-muted-foreground leading-relaxed">
                            For questions about our AI practices or to report concerns about AI-generated content, contact:{" "}
                            <a href="mailto:ai-ethics@creatorpersonaai.com" className="text-violet-400 hover:underline">
                                ai-ethics@creatorpersonaai.com
                            </a>
                        </p>
                    </section>
                </div>

                {/* Footer links */}
                <div className="mt-16 pt-8 border-t border-border/30 flex items-center gap-6 text-sm text-muted-foreground">
                    <Link href="/terms" className="hover:text-foreground transition-colors">Terms of Service</Link>
                    <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy Policy</Link>
                    <Link href="/dashboard" className="hover:text-foreground transition-colors">Back to Dashboard</Link>
                </div>
            </main>
        </div>
    );
}
